from enum import StrEnum, unique


@unique
class ButtonText(StrEnum):
    CURRENT_WEEK = "Текущая неделя"
    NEXT_WEEK = "Следующая неделя"
    PROFILE = "⚙ Профиль"
    PROFILE_PANEL_GROUP_SCHEDULE = "📚 Группа и расписание"
    PROFILE_PANEL_SETTINGS = "🔧 Настройки"
    PROFILE_PANEL_INFO = "ℹ️ Информация"
    PROFILE_BACK = "◀️ Профиль"
    CONTACT_DEVELOPER = "✉️ Написать разработчику"
    CHANGE_GROUP = "🛠 Изменить группу"
    TEACHER_SCHEDULE = "👤 Расписание преподавателя"
    SCHEDULE_BY_DATE = "📅 Расписание на день"
    SCHEDULE_LAYOUT_DAYS_ROWS = "📐 Вид: дни строками"
    SCHEDULE_LAYOUT_DAYS_COLUMNS = "📐 Вид: дни столбцами"
    ENABLE_NOTIFICATIONS = "🔔 Включить уведомления"
    DISABLE_NOTIFICATIONS = "🔕 Выключить уведомления"
    DEATH = "💀"
    CANCEL = "❌ Отмена"
    ACCEPT_USER = "✅"
    CANCEL_USER = "❌"

    ADMIN_PANEL_TITLE = "🛠 Админ-панель"
    ADMIN_MENU_STATS = "📊 Статистика"
    ADMIN_MENU_USERS = "👥 Пользователи"
    ADMIN_MENU_SEARCH = "🔍 Поиск"
    ADMIN_MENU_BROADCAST = "📣 Рассылка"
    ADMIN_BACK_MENU = "🏠 Меню"
    ADMIN_BACK_LIST = "◀ К списку"
    ADMIN_BACK_SEARCH = "◀ Назад к поиску"

    ADMIN_FILTER_ALL = "Все"
    ADMIN_FILTER_ACTIVE = "Активные"
    ADMIN_FILTER_BANNED = "Забаненные"
    ADMIN_FILTER_ADMINS = "Админы"
    ADMIN_FILTER_NOGROUP = "Без группы"

    ADMIN_PAGE_PREV = "« Назад"
    ADMIN_PAGE_NEXT = "Вперед »"

    ADMIN_SORT_BY_NAME = "🔤 Сорт.: имя"
    ADMIN_SORT_BY_SEEN = "🕒 Сорт.: посл. онлайн"
    ADMIN_SORT_LABEL_NAME = "имя/группа"
    ADMIN_SORT_LABEL_SEEN = "посл. онлайн"

    ADMIN_ACT_BAN = "🚫 Забанить"
    ADMIN_ACT_UNBAN = "✅ Разбанить"
    ADMIN_ACT_MAKE_ADMIN = "💀 Сделать админом"
    ADMIN_ACT_DROP_ADMIN = "🧹 Снять админа"
    ADMIN_ACT_DM = "✉️ Написать в ЛС"
    ADMIN_ACT_DELETE = "🗑 Удалить"
    ADMIN_ACT_DELETE_CONFIRM = "✅ Да, удалить"
    ADMIN_ACT_DELETE_CANCEL = "❌ Нет, отмена"
