version: "3"
services:
  redis:
    image: redis:7
    ports:
      - "6378:6379"

  postgres:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "5431:5432"
    volumes:
      - postgres_data_timetable_bot:/var/lib/postgresql/data

volumes:
  postgres_data_timetable_bot:
